### ISSUE TITLE
Mobile Meta

### ISSUE THREAD

**Issue by Mikeysax** [kristinh12/splurty-project#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by kristinh12** [comment]
Ok, I think I figured it out.  It definitely looks better, thank you for the suggestion!

**Comment by Mikeysax** [comment]
:+1:
